import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import NextAuthProviders from "@/providres/components/nextauth.providers";
import Providers from "@/providres/components/ReactQueryProvider.Provider";
  import { ToastContainer } from 'react-toastify';
const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight: ['400']
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${Encode.className} antialiased`}
      >
        <Providers>
          <ToastContainer></ToastContainer>
        <div className="flex flex-col justify-between min-h-screen">
          <NextAuthProviders>
          <Navbar />
          <div className="container">
            {children}
          </div>
          <Footer />
          </NextAuthProviders>
        </div>
        </Providers>
      </body>
    </html>
  );
}
